{
 "title": "TED : DB detailed view",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "DB TaskStore write time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_taskstore_write_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB TaskStore write time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_taskstore_write_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_taskstore_write_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB TaskStore read time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_taskstore_read_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB TaskStore read time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_taskstore_read_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_taskstore_read_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB collection projection",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_projection_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB collection projection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_projection_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_projection_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB Read : secondary operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_get_precompute_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB Read : secondary operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_get_precompute_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_get_precompute_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB Write : secondary operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_save_precompute_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB Write : secondary operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_save_precompute_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_save_precompute_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB access rates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(custom_counter_cql_save[1m])",
     "legendFormat": "save"
    },
    {
     "expr": "rate(custom_counter_cql_get[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(custom_counter_cql_remove[1m])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(custom_counter_cql_batch_isolated[1m])",
     "legendFormat": "isolated batch (save/remove)"
    },
    {
     "expr": "rate(custom_counter_cql_batch_unisolated[1m])",
     "legendFormat": "unisolated batch (save/remove)"
    }
   ]
  }
 ]
}