{
 "title": "TED General",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP response time",
   "type": "heatmap",
   "description": "total response time evolution",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(custom_histogram_socket_response_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP response time (Total)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "custom_histogram_socket_response_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "DB Operation : total time",
   "type": "stat",
   "description": "Median computation time to respond to write and read requests",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_write_request_bucket[5m])) by (le))",
     "legendFormat": "Write requests (50%)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_write_request_bucket[5m])) by (le))",
     "legendFormat": "Write requests (99%)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_read_request_bucket[5m])) by (le))",
     "legendFormat": "Read requests (50%)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_read_request_bucket[5m])) by (le))",
     "legendFormat": "Read requests (99%)"
    }
   ]
  },
  {
   "title": "Socket response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_socket_response_bucket[1m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_socket_response_bucket[1m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  },
  {
   "title": "DB TaskStore median computation time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_taskstore_write_bucket[1m])) by (le))",
     "legendFormat": "Write"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_taskstore_read_bucket[1m])) by (le))",
     "legendFormat": "Read"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_taskstore_remove_bucket[1m])) by (le))",
     "legendFormat": "Remove"
    }
   ]
  },
  {
   "title": "MQ Write",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(custom_histogram_mb_write_bucket[5m])) by (le))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(custom_histogram_mb_write_bucket[5m])) by (le))",
     "legendFormat": "99th centile"
    }
   ]
  }
 ]
}